-- Create 5 demo anamnes_entries for organization org_33jsHrjiy34f0X53bza5J5AiCaW
-- Simplified version without driving_license_examinations

-- Demo Entry 1: Status 'ready' - Synundersökning med bokning idag
INSERT INTO public.anamnes_entries (
  id,
  organization_id,
  form_id,
  store_id,
  first_name,
  patient_identifier,
  status,
  examination_type,
  booking_date,
  booking_id,
  is_magic_link,
  consent_given,
  consent_timestamp,
  answers,
  formatted_raw_data,
  created_at,
  sent_at
) VALUES (
  gen_random_uuid(),
  'org_33jsHrjiy34f0X53bza5J5AiCaW',
  '09d959bb-474d-47db-90d2-11f745f1512a',
  'c7c68ac0-0518-44c0-8736-a5bb3d0c7813',
  'Anna',
  'DEMO-1',
  'ready',
  'Synundersökning',
  NOW(),
  'DEMO-BOOKING-1',
  false,
  true,
  NOW() - INTERVAL '5 minutes',
  '{"current_glasses": "Ja, jag använder glasögon", "vision_problems": "Suddig syn på långt håll", "health_conditions": "Inga kända problem"}'::jsonb,
  'Nuvarande glasögon: Ja\nSynproblem: Suddig syn på långt håll\nHälsotillstånd: Inga kända problem',
  NOW() - INTERVAL '5 minutes',
  NOW() - INTERVAL '5 minutes'
);

-- Demo Entry 2: Status 'ready' - Körkortsundersökning
INSERT INTO public.anamnes_entries (
  id,
  organization_id,
  form_id,
  store_id,
  first_name,
  patient_identifier,
  status,
  examination_type,
  is_magic_link,
  consent_given,
  consent_timestamp,
  answers,
  formatted_raw_data,
  created_at,
  sent_at
) VALUES (
  gen_random_uuid(),
  'org_33jsHrjiy34f0X53bza5J5AiCaW',
  '69497d4e-682b-4ad7-aa39-d4aab9d501ed',
  'c7c68ac0-0518-44c0-8736-a5bb3d0c7813',
  'Erik',
  'DEMO-2',
  'ready',
  'Körkortsundersökning',
  false,
  true,
  NOW() - INTERVAL '1 hour',
  '{"license_type": "B", "current_vision_aid": "Inga", "health_declaration": "Inga kända hälsoproblem"}'::jsonb,
  'Körkortstyp: B\nSynhjälpmedel: Inga\nHälsodeklaration: Inga kända hälsoproblem',
  NOW() - INTERVAL '1 hour',
  NOW() - INTERVAL '1 hour'
);

-- Demo Entry 3: Status 'journaled' - Synundersökning med AI-sammanfattning
INSERT INTO public.anamnes_entries (
  id,
  organization_id,
  form_id,
  store_id,
  optician_id,
  first_name,
  patient_identifier,
  status,
  examination_type,
  is_magic_link,
  consent_given,
  consent_timestamp,
  answers,
  formatted_raw_data,
  ai_summary,
  created_at,
  sent_at,
  auto_deletion_timestamp
) VALUES (
  gen_random_uuid(),
  'org_33jsHrjiy34f0X53bza5J5AiCaW',
  '09d959bb-474d-47db-90d2-11f745f1512a',
  'c7c68ac0-0518-44c0-8736-a5bb3d0c7813',
  'user_33jsRDLjcBBiOVU8BKi0nou5dNS',
  'Maria',
  'DEMO-3',
  'journaled',
  'Synundersökning',
  false,
  true,
  NOW() - INTERVAL '3 days',
  '{"current_glasses": "Ja, progressiva glasögon", "vision_problems": "Svårt att läsa små texter", "computer_work": "6-8 timmar per dag", "health_conditions": "Diabetes typ 2"}'::jsonb,
  'Nuvarande glasögon: Ja, progressiva\nSynproblem: Svårt att läsa små texter\nDatorarbete: 6-8 timmar/dag\nHälsa: Diabetes typ 2',
  'Patient med progressiva glasögon söker för läsbesvär vid datorarbete. Arbetar 6-8h/dag vid dator. Känd diabetes typ 2 vilket kräver noggrann funduskontroll. Rekommendation: Synundersökning med särskild fokus på närsyn och diabetisk retinopati-screening.',
  NOW() - INTERVAL '3 days',
  NOW() - INTERVAL '3 days',
  NOW() + INTERVAL '45 hours'
);

-- Demo Entry 4: Status 'journaled' - Körkortsundersökning
INSERT INTO public.anamnes_entries (
  id,
  organization_id,
  form_id,
  store_id,
  optician_id,
  first_name,
  patient_identifier,
  status,
  examination_type,
  is_magic_link,
  consent_given,
  consent_timestamp,
  answers,
  formatted_raw_data,
  ai_summary,
  created_at,
  sent_at,
  auto_deletion_timestamp
) VALUES (
  gen_random_uuid(),
  'org_33jsHrjiy34f0X53bza5J5AiCaW',
  '69497d4e-682b-4ad7-aa39-d4aab9d501ed',
  'c7c68ac0-0518-44c0-8736-a5bb3d0c7813',
  'user_33jsRDLjcBBiOVU8BKi0nou5dNS',
  'Johan',
  'DEMO-4',
  'journaled',
  'Körkortsundersökning',
  false,
  true,
  NOW() - INTERVAL '2 days',
  '{"license_type": "C", "current_vision_aid": "Glasögon för bil", "vision_complaints": "Inga", "health_declaration": "God hälsa"}'::jsonb,
  'Körkortstyp: C\nSynhjälpmedel: Glasögon för bilkörning\nSynbesvär: Inga\nHälsa: God',
  'Körkortsundersökning klass C. Patient använder glasögon för bilkörning. Synschärpa med korrektion: båda ögon 1.0, höger öga 1.0, vänster öga 1.0. Godkänd för körkort klass C med villkor: Glasögon ska användas vid körning.',
  NOW() - INTERVAL '2 days',
  NOW() - INTERVAL '2 days',
  NOW() + INTERVAL '46 hours'
);

-- Demo Entry 5: Status 'sent' - Synundersökning skickad för 2 dagar sedan
INSERT INTO public.anamnes_entries (
  id,
  organization_id,
  form_id,
  store_id,
  first_name,
  patient_identifier,
  status,
  examination_type,
  booking_date,
  booking_id,
  is_magic_link,
  consent_given,
  answers,
  formatted_raw_data,
  created_at,
  sent_at
) VALUES (
  gen_random_uuid(),
  'org_33jsHrjiy34f0X53bza5J5AiCaW',
  '09d959bb-474d-47db-90d2-11f745f1512a',
  'c7c68ac0-0518-44c0-8736-a5bb3d0c7813',
  'Lisa',
  'DEMO-5',
  'sent',
  'Synundersökning',
  NOW() + INTERVAL '3 days',
  'DEMO-BOOKING-5',
  true,
  false,
  '{}'::jsonb,
  '',
  NOW() - INTERVAL '2 days',
  NOW() - INTERVAL '2 days'
);